In [1]:
import numpy as np
import time

In [2]:
x = np.random.random(1000000)

In [3]:
start = time.time()
sum(x) / len(x)
print(time.time() - start)

0.16833090782165527


In [4]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.0040204524993896484


In [5]:
x = np.array([1,2,3,4,5])

In [6]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
x.dtype

dtype('int64')

In [8]:
x.shape

(5,)

In [9]:
Y = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
Y.shape

(4, 3)

In [12]:
Y.size

12

In [14]:
x = np.zeros((3,4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
x = np.full((4, 3), 5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [16]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
X = np.diag([10, 20, 30, 50])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


In [18]:
X = np.arange(10)
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
X = np.arange(4, 10)
print(X)

[4 5 6 7 8 9]


In [20]:
X = np.arange(4, 10, 2)
print(X)

[4 6 8]


In [21]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [22]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [24]:
 x = np.random.random((3,3))
 print(x)

[[0.16436109 0.04438173 0.01475337]
 [0.67886411 0.27512061 0.31028482]
 [0.015489   0.40040945 0.435013  ]]


In [25]:
x = np.random.randint(2, 15, (3,2))
print(x)

[[ 6  6]
 [ 6 10]
 [12  9]]
